<style>
    html {
        height: 100%;
        width: 100%;
    }

    body {
        background: url("https://beedle.club/uploads/posts/2023-03/1679617264_beedle-club-p-fentezi-art-priroda-fentezi-vkontakte-4.jpg") no-repeat center center fixed;
        background-size: cover;
        font-family: "Droid Serif", serif;
    }

    #container {
        background: rgba(230, 230, 250, 0.5);
        width: 18.75rem;
        height: 25rem;
        margin: auto;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
    }

    header {
        text-align: center;
        vertical-align: middle;
        line-height: 3rem;
        height: 3rem;
        background: rgba(216, 191, 216, 0.7);
        font-size: 1.4rem;
        color: black;
    }

    fieldset {
        border: 0;
        text-align: center;
    }

    input[type="submit"] {
        background: rgba(0, 0, 0, 1);
        border: 0;
        display: block;
        width: 70%;
        margin: 0 auto;
        color: white;
        padding: 0.7rem;
        cursor: pointer;
    }

    input {
        background: transparent;
        border: 0;
        border-left: 4px solid;
        border-color: black;
        padding: 10px;
        color: black;
    }

    input[type="text"]:focus,
    input[type="email"]:focus,
    input[type="password"]:focus {
        outline: 0;
        background: rgba(0, 0, 0, 0.3);
        border-radius: 1.2rem;
        border-color: transparent;
    }

    ::placeholder {
        color: black;
    }

    /*Media queries */

    @media all and (min-width: 481px) and (max-width: 568px) {
        #container {
            margin-top: 10%;
            margin-bottom: 10%;
        }
    }

    @media all and (min-width: 569px) and (max-width: 768px) {
        #container {
            margin-top: 5%;
            margin-bottom: 5%;
        }
    }
</style>
<body>
<div id="container">
    <header>Register new account</header>
    <form method="post">
        <fieldset>
            <br/>
            <label style="color: red"> <?php if (isset($errors['name'])) {
                    echo $errors['name'];
                } ?></label>
            <input type="text" name="name" id="name" placeholder="Username">
            <br/><br/>
            <label style="color: red"> <?php if (isset($errors['email'])) {
                    echo $errors['email'];
                } ?></label>
            <input type="text" name="email" id="email" placeholder="E-mail">
            <br/><br/>
            <label style="color: red"> <?php if (isset($errors['password'])) {
                    echo $errors['password'];
                } ?></label>
            <input type="password" name="password" id="password" placeholder="Password">
            <br/><br/>
            <label style="color: red"> <?php if (isset($errors['confirm-password'])) {
                    echo $errors['confirm-password'];
                } ?></label>
            <input type="password" name="confirm-password" id="confirm-password" placeholder="Confirm Password">
            <br/> <br/> <br/>
            <label for="submit"></label>
            <input type="submit" name="submit" id="submit" value="REGISTER">
        </fieldset>
    </form>
</div>
</body>